spring:
  datasource:
    url: jdbc:h2:~/data/board
  #  datasource:
#    driver-class-name:
#    url:
#    username: root
#    password:
#      data: classpath:schema.sql
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: create

logging:
  level:
    org:
      springframework:
      hibernate:
        type:
          descriptor:
            sql: trace
